cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/nco/simulation/submodules/nco_nco_ii_0_sin.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/nco/simulation/submodules/nco_nco_ii_0_cos.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twi5.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twi1.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twr4.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twr5.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twr1.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twi2.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twi3.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twr2.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twi4.hex ./
cp -f /homes/user/stud/fall21/mhr2154/Documents/fft_sim/fft/simulation/submodules/fft_fft_ii_0_opt_twr3.hex ./
