# TCL File Generated by Component Editor 21.1
# Mon May 06 21:57:23 EDT 2024
# DO NOT MODIFY


# 
# standard_4096_buffer "Standard 4096 Buffer" v1.0
#  2024.05.06.21:57:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module standard_4096_buffer
# 
set_module_property DESCRIPTION ""
set_module_property NAME standard_4096_buffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Standard 4096 Buffer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file buffer.v VERILOG PATH buffer.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point a_connect
# 
add_interface a_connect conduit end
set_interface_property a_connect associatedClock ""
set_interface_property a_connect associatedReset ""
set_interface_property a_connect ENABLED true
set_interface_property a_connect EXPORT_OF ""
set_interface_property a_connect PORT_NAME_MAP ""
set_interface_property a_connect CMSIS_SVD_VARIABLES ""
set_interface_property a_connect SVD_ADDRESS_GROUP ""

add_interface_port a_connect address_a address Input 9
add_interface_port a_connect data_a datain Input 16
add_interface_port a_connect q_a dataout Output 16
add_interface_port a_connect wren_a writeenable Input 1


# 
# connection point a_clock
# 
add_interface a_clock clock end
set_interface_property a_clock clockRate 0
set_interface_property a_clock ENABLED true
set_interface_property a_clock EXPORT_OF ""
set_interface_property a_clock PORT_NAME_MAP ""
set_interface_property a_clock CMSIS_SVD_VARIABLES ""
set_interface_property a_clock SVD_ADDRESS_GROUP ""

add_interface_port a_clock clock_a clk Input 1


# 
# connection point b_clock
# 
add_interface b_clock clock end
set_interface_property b_clock clockRate 0
set_interface_property b_clock ENABLED true
set_interface_property b_clock EXPORT_OF ""
set_interface_property b_clock PORT_NAME_MAP ""
set_interface_property b_clock CMSIS_SVD_VARIABLES ""
set_interface_property b_clock SVD_ADDRESS_GROUP ""

add_interface_port b_clock clock_b clk Input 1


# 
# connection point b_connect
# 
add_interface b_connect conduit end
set_interface_property b_connect associatedClock a_clock
set_interface_property b_connect associatedReset ""
set_interface_property b_connect ENABLED true
set_interface_property b_connect EXPORT_OF ""
set_interface_property b_connect PORT_NAME_MAP ""
set_interface_property b_connect CMSIS_SVD_VARIABLES ""
set_interface_property b_connect SVD_ADDRESS_GROUP ""

add_interface_port b_connect address_b address Input 9
add_interface_port b_connect data_b datain Input 16
add_interface_port b_connect q_b dataout Output 16
add_interface_port b_connect wren_b writeenable Input 1

