# TCL File Generated by Component Editor 21.1
# Mon May 06 21:21:08 EDT 2024
# DO NOT MODIFY


# 
# pitch_shifter "Pitch Shifter" v1.0
#  2024.05.06.21:21:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pitch_shifter
# 
set_module_property DESCRIPTION ""
set_module_property NAME pitch_shifter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Pitch Shifter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pitch_shifter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pitch_shifter.sv SYSTEM_VERILOG PATH pitch_shifter/pitch_shifter.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BUFFER_SIZE INTEGER 1024
set_parameter_property BUFFER_SIZE DEFAULT_VALUE 1024
set_parameter_property BUFFER_SIZE DISPLAY_NAME BUFFER_SIZE
set_parameter_property BUFFER_SIZE TYPE INTEGER
set_parameter_property BUFFER_SIZE UNITS None
set_parameter_property BUFFER_SIZE HDL_PARAMETER true
add_parameter DATA_SIZE INTEGER 24
set_parameter_property DATA_SIZE DEFAULT_VALUE 24
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE INTEGER
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 out_left writeresponsevalid_n Output "((DATA_SIZE-1)) - (0) + 1"
add_interface_port avalon_slave_0 out_right writeresponsevalid_n Output "((DATA_SIZE-1)) - (0) + 1"
add_interface_port avalon_slave_0 out_ready writeresponsevalid_n Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point codec_to_pitch_shifter
# 
add_interface codec_to_pitch_shifter conduit end
set_interface_property codec_to_pitch_shifter associatedClock clock
set_interface_property codec_to_pitch_shifter associatedReset ""
set_interface_property codec_to_pitch_shifter ENABLED true
set_interface_property codec_to_pitch_shifter EXPORT_OF ""
set_interface_property codec_to_pitch_shifter PORT_NAME_MAP ""
set_interface_property codec_to_pitch_shifter CMSIS_SVD_VARIABLES ""
set_interface_property codec_to_pitch_shifter SVD_ADDRESS_GROUP ""

add_interface_port codec_to_pitch_shifter in_left beginbursttransfer Input "((DATA_SIZE-1)) - (0) + 1"
add_interface_port codec_to_pitch_shifter in_ready beginbursttransfer Input 1
add_interface_port codec_to_pitch_shifter in_right beginbursttransfer Input "((DATA_SIZE-1)) - (0) + 1"


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1

