# TCL File Generated by Component Editor 21.1
# Sun May 12 05:53:51 EDT 2024
# DO NOT MODIFY


# 
# emitter "Emitter" v1.0
#  2024.05.12.05:53:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module emitter
# 
set_module_property DESCRIPTION ""
set_module_property NAME emitter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Emitter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL emitter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file emitter.sv SYSTEM_VERILOG PATH components/emitter/emitter.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point from_stitcher
# 
add_interface from_stitcher conduit end
set_interface_property from_stitcher associatedClock ""
set_interface_property from_stitcher associatedReset ""
set_interface_property from_stitcher ENABLED true
set_interface_property from_stitcher EXPORT_OF ""
set_interface_property from_stitcher PORT_NAME_MAP ""
set_interface_property from_stitcher CMSIS_SVD_VARIABLES ""
set_interface_property from_stitcher SVD_ADDRESS_GROUP ""

add_interface_port from_stitcher go_in go Input 1
add_interface_port from_stitcher window_start data Input 2


# 
# connection point left_out
# 
add_interface left_out avalon_streaming start
set_interface_property left_out associatedClock clock
set_interface_property left_out associatedReset reset_sink
set_interface_property left_out dataBitsPerSymbol 8
set_interface_property left_out errorDescriptor ""
set_interface_property left_out firstSymbolInHighOrderBits true
set_interface_property left_out maxChannel 0
set_interface_property left_out readyLatency 0
set_interface_property left_out ENABLED true
set_interface_property left_out EXPORT_OF ""
set_interface_property left_out PORT_NAME_MAP ""
set_interface_property left_out CMSIS_SVD_VARIABLES ""
set_interface_property left_out SVD_ADDRESS_GROUP ""

add_interface_port left_out left_out_data data Output 16
add_interface_port left_out left_out_ready ready Input 1
add_interface_port left_out left_out_valid valid Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point right_out
# 
add_interface right_out avalon_streaming start
set_interface_property right_out associatedClock clock
set_interface_property right_out associatedReset reset_sink
set_interface_property right_out dataBitsPerSymbol 8
set_interface_property right_out errorDescriptor ""
set_interface_property right_out firstSymbolInHighOrderBits true
set_interface_property right_out maxChannel 0
set_interface_property right_out readyLatency 0
set_interface_property right_out ENABLED true
set_interface_property right_out EXPORT_OF ""
set_interface_property right_out PORT_NAME_MAP ""
set_interface_property right_out CMSIS_SVD_VARIABLES ""
set_interface_property right_out SVD_ADDRESS_GROUP ""

add_interface_port right_out right_out_data data Output 16
add_interface_port right_out right_out_valid valid Output 1
add_interface_port right_out right_out_ready ready Input 1


# 
# connection point r_out_buf
# 
add_interface r_out_buf conduit end
set_interface_property r_out_buf associatedClock ""
set_interface_property r_out_buf associatedReset ""
set_interface_property r_out_buf ENABLED true
set_interface_property r_out_buf EXPORT_OF ""
set_interface_property r_out_buf PORT_NAME_MAP ""
set_interface_property r_out_buf CMSIS_SVD_VARIABLES ""
set_interface_property r_out_buf SVD_ADDRESS_GROUP ""

add_interface_port r_out_buf in_buf_data data Input 16
add_interface_port r_out_buf in_buf_addr addr Output 12

