# TCL File Generated by Component Editor 21.1
# Sun May 12 04:35:47 EDT 2024
# DO NOT MODIFY


# 
# ffter "FFTer" v1.0
#  2024.05.12.04:35:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ffter
# 
set_module_property DESCRIPTION ""
set_module_property NAME ffter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FFTer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ffter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ffter.sv SYSTEM_VERILOG PATH components/ffter/ffter.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point from_first_hannifier
# 
add_interface from_first_hannifier conduit end
set_interface_property from_first_hannifier associatedClock ""
set_interface_property from_first_hannifier associatedReset ""
set_interface_property from_first_hannifier ENABLED true
set_interface_property from_first_hannifier EXPORT_OF ""
set_interface_property from_first_hannifier PORT_NAME_MAP ""
set_interface_property from_first_hannifier CMSIS_SVD_VARIABLES ""
set_interface_property from_first_hannifier SVD_ADDRESS_GROUP ""

add_interface_port from_first_hannifier go_in go Input 1


# 
# connection point to_cart_to_polar
# 
add_interface to_cart_to_polar conduit end
set_interface_property to_cart_to_polar associatedClock ""
set_interface_property to_cart_to_polar associatedReset ""
set_interface_property to_cart_to_polar ENABLED true
set_interface_property to_cart_to_polar EXPORT_OF ""
set_interface_property to_cart_to_polar PORT_NAME_MAP ""
set_interface_property to_cart_to_polar CMSIS_SVD_VARIABLES ""
set_interface_property to_cart_to_polar SVD_ADDRESS_GROUP ""

add_interface_port to_cart_to_polar go_out go Output 1


# 
# connection point r_pre_fft_buf
# 
add_interface r_pre_fft_buf conduit end
set_interface_property r_pre_fft_buf associatedClock ""
set_interface_property r_pre_fft_buf associatedReset ""
set_interface_property r_pre_fft_buf ENABLED true
set_interface_property r_pre_fft_buf EXPORT_OF ""
set_interface_property r_pre_fft_buf PORT_NAME_MAP ""
set_interface_property r_pre_fft_buf CMSIS_SVD_VARIABLES ""
set_interface_property r_pre_fft_buf SVD_ADDRESS_GROUP ""

add_interface_port r_pre_fft_buf in_buf_addr addr Output 12
add_interface_port r_pre_fft_buf in_buf_data data Input 16


# 
# connection point w_post_fft_imag_buf
# 
add_interface w_post_fft_imag_buf conduit end
set_interface_property w_post_fft_imag_buf associatedClock ""
set_interface_property w_post_fft_imag_buf associatedReset ""
set_interface_property w_post_fft_imag_buf ENABLED true
set_interface_property w_post_fft_imag_buf EXPORT_OF ""
set_interface_property w_post_fft_imag_buf PORT_NAME_MAP ""
set_interface_property w_post_fft_imag_buf CMSIS_SVD_VARIABLES ""
set_interface_property w_post_fft_imag_buf SVD_ADDRESS_GROUP ""

add_interface_port w_post_fft_imag_buf imag_buf_data data Output 16
add_interface_port w_post_fft_imag_buf imag_buf_addr addr Output 12
add_interface_port w_post_fft_imag_buf imag_buf_wren wren Output 1


# 
# connection point w_post_fft_real_buf
# 
add_interface w_post_fft_real_buf conduit end
set_interface_property w_post_fft_real_buf associatedClock ""
set_interface_property w_post_fft_real_buf associatedReset ""
set_interface_property w_post_fft_real_buf ENABLED true
set_interface_property w_post_fft_real_buf EXPORT_OF ""
set_interface_property w_post_fft_real_buf PORT_NAME_MAP ""
set_interface_property w_post_fft_real_buf CMSIS_SVD_VARIABLES ""
set_interface_property w_post_fft_real_buf SVD_ADDRESS_GROUP ""

add_interface_port w_post_fft_real_buf real_buf_addr addr Output 12
add_interface_port w_post_fft_real_buf real_buf_data data Output 16
add_interface_port w_post_fft_real_buf real_buf_wren wren Output 1

