# TCL File Generated by Component Editor 21.1
# Sun May 12 04:10:35 EDT 2024
# DO NOT MODIFY


# 
# hann_rom "Hann ROM" v1.0
#  2024.05.12.04:10:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hann_rom
# 
set_module_property DESCRIPTION ""
set_module_property NAME hann_rom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Hann ROM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hann_rom
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hann_rom.v VERILOG PATH components/memblocks/hann_rom/hann_rom.v TOP_LEVEL_FILE
add_fileset_file hann_rom_bb.v VERILOG PATH components/memblocks/hann_rom/hann_rom_bb.v
add_fileset_file hann_rom_inst.v VERILOG PATH components/memblocks/hann_rom/hann_rom_inst.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clock clk Input 1


# 
# connection point reader_b
# 
add_interface reader_b conduit end
set_interface_property reader_b associatedClock ""
set_interface_property reader_b associatedReset ""
set_interface_property reader_b ENABLED true
set_interface_property reader_b EXPORT_OF ""
set_interface_property reader_b PORT_NAME_MAP ""
set_interface_property reader_b CMSIS_SVD_VARIABLES ""
set_interface_property reader_b SVD_ADDRESS_GROUP ""

add_interface_port reader_b q_b data Output 16
add_interface_port reader_b address_b addr Input 12


# 
# connection point reader_a
# 
add_interface reader_a conduit end
set_interface_property reader_a associatedClock ""
set_interface_property reader_a associatedReset ""
set_interface_property reader_a ENABLED true
set_interface_property reader_a EXPORT_OF ""
set_interface_property reader_a PORT_NAME_MAP ""
set_interface_property reader_a CMSIS_SVD_VARIABLES ""
set_interface_property reader_a SVD_ADDRESS_GROUP ""

add_interface_port reader_a address_a addr Input 12
add_interface_port reader_a q_a data Output 16

