# TCL File Generated by Component Editor 21.1
# Sun May 12 05:09:59 EDT 2024
# DO NOT MODIFY


# 
# polar_to_cart "Polar to Cart" v1.0
#  2024.05.12.05:09:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module polar_to_cart
# 
set_module_property DESCRIPTION ""
set_module_property NAME polar_to_cart
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Polar to Cart"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL polar_to_cart
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file polar_to_cart.sv SYSTEM_VERILOG PATH components/polar_to_cart/polar_to_cart.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point from_scaler
# 
add_interface from_scaler conduit end
set_interface_property from_scaler associatedClock ""
set_interface_property from_scaler associatedReset ""
set_interface_property from_scaler ENABLED true
set_interface_property from_scaler EXPORT_OF ""
set_interface_property from_scaler PORT_NAME_MAP ""
set_interface_property from_scaler CMSIS_SVD_VARIABLES ""
set_interface_property from_scaler SVD_ADDRESS_GROUP ""

add_interface_port from_scaler cur_window data Input 1
add_interface_port from_scaler go_in go Input 1


# 
# connection point r_post_scaler_mag_buf_0
# 
add_interface r_post_scaler_mag_buf_0 conduit end
set_interface_property r_post_scaler_mag_buf_0 associatedClock ""
set_interface_property r_post_scaler_mag_buf_0 associatedReset ""
set_interface_property r_post_scaler_mag_buf_0 ENABLED true
set_interface_property r_post_scaler_mag_buf_0 EXPORT_OF ""
set_interface_property r_post_scaler_mag_buf_0 PORT_NAME_MAP ""
set_interface_property r_post_scaler_mag_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property r_post_scaler_mag_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port r_post_scaler_mag_buf_0 mag_buf_0_addr addr Output 12
add_interface_port r_post_scaler_mag_buf_0 mag_buf_0_data data Input 16


# 
# connection point r_post_scaler_mag_buf_1
# 
add_interface r_post_scaler_mag_buf_1 conduit end
set_interface_property r_post_scaler_mag_buf_1 associatedClock ""
set_interface_property r_post_scaler_mag_buf_1 associatedReset ""
set_interface_property r_post_scaler_mag_buf_1 ENABLED true
set_interface_property r_post_scaler_mag_buf_1 EXPORT_OF ""
set_interface_property r_post_scaler_mag_buf_1 PORT_NAME_MAP ""
set_interface_property r_post_scaler_mag_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property r_post_scaler_mag_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port r_post_scaler_mag_buf_1 mag_buf_1_addr addr Output 12
add_interface_port r_post_scaler_mag_buf_1 mag_buf_1_data data Input 16


# 
# connection point r_post_scaler_phase_buf_0
# 
add_interface r_post_scaler_phase_buf_0 conduit end
set_interface_property r_post_scaler_phase_buf_0 associatedClock ""
set_interface_property r_post_scaler_phase_buf_0 associatedReset ""
set_interface_property r_post_scaler_phase_buf_0 ENABLED true
set_interface_property r_post_scaler_phase_buf_0 EXPORT_OF ""
set_interface_property r_post_scaler_phase_buf_0 PORT_NAME_MAP ""
set_interface_property r_post_scaler_phase_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property r_post_scaler_phase_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port r_post_scaler_phase_buf_0 phase_buf_0_addr addr Output 12
add_interface_port r_post_scaler_phase_buf_0 phase_buf_0_data data Input 16


# 
# connection point r_post_scaler_phase_buf_1
# 
add_interface r_post_scaler_phase_buf_1 conduit end
set_interface_property r_post_scaler_phase_buf_1 associatedClock ""
set_interface_property r_post_scaler_phase_buf_1 associatedReset ""
set_interface_property r_post_scaler_phase_buf_1 ENABLED true
set_interface_property r_post_scaler_phase_buf_1 EXPORT_OF ""
set_interface_property r_post_scaler_phase_buf_1 PORT_NAME_MAP ""
set_interface_property r_post_scaler_phase_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property r_post_scaler_phase_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port r_post_scaler_phase_buf_1 phase_buf_1_addr addr Output 12
add_interface_port r_post_scaler_phase_buf_1 phase_buf_1_data data Input 16


# 
# connection point w_pre_ifft_real_buf
# 
add_interface w_pre_ifft_real_buf conduit end
set_interface_property w_pre_ifft_real_buf associatedClock ""
set_interface_property w_pre_ifft_real_buf associatedReset ""
set_interface_property w_pre_ifft_real_buf ENABLED true
set_interface_property w_pre_ifft_real_buf EXPORT_OF ""
set_interface_property w_pre_ifft_real_buf PORT_NAME_MAP ""
set_interface_property w_pre_ifft_real_buf CMSIS_SVD_VARIABLES ""
set_interface_property w_pre_ifft_real_buf SVD_ADDRESS_GROUP ""

add_interface_port w_pre_ifft_real_buf real_buf_addr addr Output 12
add_interface_port w_pre_ifft_real_buf real_buf_data data Output 16
add_interface_port w_pre_ifft_real_buf real_buf_wren wren Output 1


# 
# connection point w_pre_ifft_imag_buf
# 
add_interface w_pre_ifft_imag_buf conduit end
set_interface_property w_pre_ifft_imag_buf associatedClock ""
set_interface_property w_pre_ifft_imag_buf associatedReset ""
set_interface_property w_pre_ifft_imag_buf ENABLED true
set_interface_property w_pre_ifft_imag_buf EXPORT_OF ""
set_interface_property w_pre_ifft_imag_buf PORT_NAME_MAP ""
set_interface_property w_pre_ifft_imag_buf CMSIS_SVD_VARIABLES ""
set_interface_property w_pre_ifft_imag_buf SVD_ADDRESS_GROUP ""

add_interface_port w_pre_ifft_imag_buf imag_buf_addr addr Output 12
add_interface_port w_pre_ifft_imag_buf imag_buf_data data Output 16
add_interface_port w_pre_ifft_imag_buf imag_buf_wren wren Output 1


# 
# connection point to_iffter
# 
add_interface to_iffter conduit end
set_interface_property to_iffter associatedClock ""
set_interface_property to_iffter associatedReset ""
set_interface_property to_iffter ENABLED true
set_interface_property to_iffter EXPORT_OF ""
set_interface_property to_iffter PORT_NAME_MAP ""
set_interface_property to_iffter CMSIS_SVD_VARIABLES ""
set_interface_property to_iffter SVD_ADDRESS_GROUP ""

add_interface_port to_iffter go_out go Output 1

