# TCL File Generated by Component Editor 21.1
# Sun May 12 05:07:04 EDT 2024
# DO NOT MODIFY


# 
# r_rw_buf "R RW Buf" v1.0
#  2024.05.12.05:07:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module r_rw_buf
# 
set_module_property DESCRIPTION ""
set_module_property NAME r_rw_buf
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "R RW Buf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL r_rw_buf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file r_rw_buf.v VERILOG PATH components/memblocks/r_rw_buf/r_rw_buf.v TOP_LEVEL_FILE
add_fileset_file r_rw_buf_bb.v VERILOG PATH components/memblocks/r_rw_buf/r_rw_buf_bb.v
add_fileset_file r_rw_buf_inst.v VERILOG PATH components/memblocks/r_rw_buf/r_rw_buf_inst.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point memrwer
# 
add_interface memrwer conduit end
set_interface_property memrwer associatedClock ""
set_interface_property memrwer associatedReset ""
set_interface_property memrwer ENABLED true
set_interface_property memrwer EXPORT_OF ""
set_interface_property memrwer PORT_NAME_MAP ""
set_interface_property memrwer CMSIS_SVD_VARIABLES ""
set_interface_property memrwer SVD_ADDRESS_GROUP ""

add_interface_port memrwer data_b wrdata Input 16
add_interface_port memrwer wren_b wren Input 1
add_interface_port memrwer q_b rdata Output 16
add_interface_port memrwer address_b raddr Input 12
add_interface_port memrwer waddr_b wraddr Input 12


# 
# connection point memreader
# 
add_interface memreader conduit end
set_interface_property memreader associatedClock ""
set_interface_property memreader associatedReset ""
set_interface_property memreader ENABLED true
set_interface_property memreader EXPORT_OF ""
set_interface_property memreader PORT_NAME_MAP ""
set_interface_property memreader CMSIS_SVD_VARIABLES ""
set_interface_property memreader SVD_ADDRESS_GROUP ""

add_interface_port memreader address_a addr Input 12
add_interface_port memreader data_a data Output 16

