# TCL File Generated by Component Editor 21.1
# Sun May 12 03:19:07 EDT 2024
# DO NOT MODIFY


# 
# ring_buf "Ring Buffer" v1.0
#  2024.05.12.03:19:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ring_buf
# 
set_module_property DESCRIPTION ""
set_module_property NAME ring_buf
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Ring Buffer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ring_buf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ring_buf.v VERILOG PATH components/memblocks/ring_buf/ring_buf.v TOP_LEVEL_FILE
add_fileset_file ring_buf_bb.v VERILOG PATH components/memblocks/ring_buf/ring_buf_bb.v
add_fileset_file ring_buf_inst.v VERILOG PATH components/memblocks/ring_buf/ring_buf_inst.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point memreader
# 
add_interface memreader conduit end
set_interface_property memreader associatedClock ""
set_interface_property memreader associatedReset ""
set_interface_property memreader ENABLED true
set_interface_property memreader EXPORT_OF ""
set_interface_property memreader PORT_NAME_MAP ""
set_interface_property memreader CMSIS_SVD_VARIABLES ""
set_interface_property memreader SVD_ADDRESS_GROUP ""

add_interface_port memreader q data Output 16
add_interface_port memreader rdaddress addr Input 13


# 
# connection point memwriter
# 
add_interface memwriter conduit end
set_interface_property memwriter associatedClock ""
set_interface_property memwriter associatedReset ""
set_interface_property memwriter ENABLED true
set_interface_property memwriter EXPORT_OF ""
set_interface_property memwriter PORT_NAME_MAP ""
set_interface_property memwriter CMSIS_SVD_VARIABLES ""
set_interface_property memwriter SVD_ADDRESS_GROUP ""

add_interface_port memwriter wraddress addr Input 13
add_interface_port memwriter wren wren Input 1
add_interface_port memwriter data data Input 16


# 
# connection point readclk
# 
add_interface readclk clock end
set_interface_property readclk clockRate 0
set_interface_property readclk ENABLED true
set_interface_property readclk EXPORT_OF ""
set_interface_property readclk PORT_NAME_MAP ""
set_interface_property readclk CMSIS_SVD_VARIABLES ""
set_interface_property readclk SVD_ADDRESS_GROUP ""

add_interface_port readclk rdclock clk Input 1


# 
# connection point wrclock
# 
add_interface wrclock clock end
set_interface_property wrclock clockRate 0
set_interface_property wrclock ENABLED true
set_interface_property wrclock EXPORT_OF ""
set_interface_property wrclock PORT_NAME_MAP ""
set_interface_property wrclock CMSIS_SVD_VARIABLES ""
set_interface_property wrclock SVD_ADDRESS_GROUP ""

add_interface_port wrclock wrclock clk Input 1

