# TCL File Generated by Component Editor 21.1
# Sun May 12 04:27:52 EDT 2024
# DO NOT MODIFY


# 
# sampler "Sampler" v1.0
#  2024.05.12.04:27:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sampler
# 
set_module_property DESCRIPTION ""
set_module_property NAME sampler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Sampler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sampler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sampler.sv SYSTEM_VERILOG PATH components/sampler/sampler.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point left_in
# 
add_interface left_in avalon_streaming end
set_interface_property left_in associatedClock clock
set_interface_property left_in associatedReset reset_sink
set_interface_property left_in dataBitsPerSymbol 8
set_interface_property left_in errorDescriptor ""
set_interface_property left_in firstSymbolInHighOrderBits true
set_interface_property left_in maxChannel 0
set_interface_property left_in readyLatency 0
set_interface_property left_in ENABLED true
set_interface_property left_in EXPORT_OF ""
set_interface_property left_in PORT_NAME_MAP ""
set_interface_property left_in CMSIS_SVD_VARIABLES ""
set_interface_property left_in SVD_ADDRESS_GROUP ""

add_interface_port left_in left_in_data data Input 16
add_interface_port left_in left_in_ready ready Output 1
add_interface_port left_in left_in_valid valid Input 1


# 
# connection point right_in
# 
add_interface right_in avalon_streaming end
set_interface_property right_in associatedClock clock
set_interface_property right_in associatedReset reset_sink
set_interface_property right_in dataBitsPerSymbol 8
set_interface_property right_in errorDescriptor ""
set_interface_property right_in firstSymbolInHighOrderBits true
set_interface_property right_in maxChannel 0
set_interface_property right_in readyLatency 0
set_interface_property right_in ENABLED true
set_interface_property right_in EXPORT_OF ""
set_interface_property right_in PORT_NAME_MAP ""
set_interface_property right_in CMSIS_SVD_VARIABLES ""
set_interface_property right_in SVD_ADDRESS_GROUP ""

add_interface_port right_in right_in_data data Input 16
add_interface_port right_in right_in_ready ready Output 1
add_interface_port right_in right_in_valid valid Input 1


# 
# connection point to_ring_buf
# 
add_interface to_ring_buf conduit end
set_interface_property to_ring_buf associatedClock ""
set_interface_property to_ring_buf associatedReset ""
set_interface_property to_ring_buf ENABLED true
set_interface_property to_ring_buf EXPORT_OF ""
set_interface_property to_ring_buf PORT_NAME_MAP ""
set_interface_property to_ring_buf CMSIS_SVD_VARIABLES ""
set_interface_property to_ring_buf SVD_ADDRESS_GROUP ""

add_interface_port to_ring_buf ring_buf_addr addr Output 13
add_interface_port to_ring_buf ring_buf_data data Output 16
add_interface_port to_ring_buf ring_buf_wren wren Output 1


# 
# connection point to_first_hannifier
# 
add_interface to_first_hannifier conduit end
set_interface_property to_first_hannifier associatedClock ""
set_interface_property to_first_hannifier associatedReset ""
set_interface_property to_first_hannifier ENABLED true
set_interface_property to_first_hannifier EXPORT_OF ""
set_interface_property to_first_hannifier PORT_NAME_MAP ""
set_interface_property to_first_hannifier CMSIS_SVD_VARIABLES ""
set_interface_property to_first_hannifier SVD_ADDRESS_GROUP ""

add_interface_port to_first_hannifier window_start data Output 3
add_interface_port to_first_hannifier go_out go Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1

