# TCL File Generated by Component Editor 21.1
# Sun May 12 02:56:13 EDT 2024
# DO NOT MODIFY


# 
# scaler "Scaler" v1.0
#  2024.05.12.02:56:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module scaler
# 
set_module_property DESCRIPTION ""
set_module_property NAME scaler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Scaler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL scaler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file scaler.sv SYSTEM_VERILOG PATH components/scaler/scaler.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point from_cart_to_polar
# 
add_interface from_cart_to_polar conduit end
set_interface_property from_cart_to_polar associatedClock ""
set_interface_property from_cart_to_polar associatedReset ""
set_interface_property from_cart_to_polar ENABLED true
set_interface_property from_cart_to_polar EXPORT_OF ""
set_interface_property from_cart_to_polar PORT_NAME_MAP ""
set_interface_property from_cart_to_polar CMSIS_SVD_VARIABLES ""
set_interface_property from_cart_to_polar SVD_ADDRESS_GROUP ""

add_interface_port from_cart_to_polar cur_window data Input 1
add_interface_port from_cart_to_polar go_in go Input 1


# 
# connection point r_pre_scaler_mag_buf_0
# 
add_interface r_pre_scaler_mag_buf_0 conduit end
set_interface_property r_pre_scaler_mag_buf_0 associatedClock ""
set_interface_property r_pre_scaler_mag_buf_0 associatedReset ""
set_interface_property r_pre_scaler_mag_buf_0 ENABLED true
set_interface_property r_pre_scaler_mag_buf_0 EXPORT_OF ""
set_interface_property r_pre_scaler_mag_buf_0 PORT_NAME_MAP ""
set_interface_property r_pre_scaler_mag_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property r_pre_scaler_mag_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port r_pre_scaler_mag_buf_0 mag_in_buf_0_addr addr Output 12
add_interface_port r_pre_scaler_mag_buf_0 mag_in_buf_0_data data Input 16


# 
# connection point r_pre_scaler_mag_buf_1
# 
add_interface r_pre_scaler_mag_buf_1 conduit end
set_interface_property r_pre_scaler_mag_buf_1 associatedClock ""
set_interface_property r_pre_scaler_mag_buf_1 associatedReset ""
set_interface_property r_pre_scaler_mag_buf_1 ENABLED true
set_interface_property r_pre_scaler_mag_buf_1 EXPORT_OF ""
set_interface_property r_pre_scaler_mag_buf_1 PORT_NAME_MAP ""
set_interface_property r_pre_scaler_mag_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property r_pre_scaler_mag_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port r_pre_scaler_mag_buf_1 mag_in_buf_1_addr addr Output 12
add_interface_port r_pre_scaler_mag_buf_1 mag_in_buf_1_data data Input 16


# 
# connection point r_pre_scaler_phase_buf_0
# 
add_interface r_pre_scaler_phase_buf_0 conduit end
set_interface_property r_pre_scaler_phase_buf_0 associatedClock ""
set_interface_property r_pre_scaler_phase_buf_0 associatedReset ""
set_interface_property r_pre_scaler_phase_buf_0 ENABLED true
set_interface_property r_pre_scaler_phase_buf_0 EXPORT_OF ""
set_interface_property r_pre_scaler_phase_buf_0 PORT_NAME_MAP ""
set_interface_property r_pre_scaler_phase_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property r_pre_scaler_phase_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port r_pre_scaler_phase_buf_0 phase_in_buf_0_addr addr Output 12
add_interface_port r_pre_scaler_phase_buf_0 phase_in_buf_0_data data Input 16


# 
# connection point r_pre_scaler_phase_buf_1
# 
add_interface r_pre_scaler_phase_buf_1 conduit end
set_interface_property r_pre_scaler_phase_buf_1 associatedClock ""
set_interface_property r_pre_scaler_phase_buf_1 associatedReset ""
set_interface_property r_pre_scaler_phase_buf_1 ENABLED true
set_interface_property r_pre_scaler_phase_buf_1 EXPORT_OF ""
set_interface_property r_pre_scaler_phase_buf_1 PORT_NAME_MAP ""
set_interface_property r_pre_scaler_phase_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property r_pre_scaler_phase_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port r_pre_scaler_phase_buf_1 phase_in_buf_1_addr addr Output 12
add_interface_port r_pre_scaler_phase_buf_1 phase_in_buf_1_data data Input 16


# 
# connection point rw_post_scaler_phase_buf_0
# 
add_interface rw_post_scaler_phase_buf_0 conduit end
set_interface_property rw_post_scaler_phase_buf_0 associatedClock ""
set_interface_property rw_post_scaler_phase_buf_0 associatedReset ""
set_interface_property rw_post_scaler_phase_buf_0 ENABLED true
set_interface_property rw_post_scaler_phase_buf_0 EXPORT_OF ""
set_interface_property rw_post_scaler_phase_buf_0 PORT_NAME_MAP ""
set_interface_property rw_post_scaler_phase_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property rw_post_scaler_phase_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port rw_post_scaler_phase_buf_0 phase_out_buf_0_raddr raddr Output 12
add_interface_port rw_post_scaler_phase_buf_0 phase_out_buf_0_rdata rdata Input 16
add_interface_port rw_post_scaler_phase_buf_0 phase_out_buf_0_wraddr wraddr Output 12
add_interface_port rw_post_scaler_phase_buf_0 phase_out_buf_0_wrdata wrdata Output 16
add_interface_port rw_post_scaler_phase_buf_0 phase_out_buf_0_wren wren Output 1


# 
# connection point rw_post_scaler_phase_buf_1
# 
add_interface rw_post_scaler_phase_buf_1 conduit end
set_interface_property rw_post_scaler_phase_buf_1 associatedClock ""
set_interface_property rw_post_scaler_phase_buf_1 associatedReset ""
set_interface_property rw_post_scaler_phase_buf_1 ENABLED true
set_interface_property rw_post_scaler_phase_buf_1 EXPORT_OF ""
set_interface_property rw_post_scaler_phase_buf_1 PORT_NAME_MAP ""
set_interface_property rw_post_scaler_phase_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property rw_post_scaler_phase_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port rw_post_scaler_phase_buf_1 phase_out_buf_1_raddr raddr Output 12
add_interface_port rw_post_scaler_phase_buf_1 phase_out_buf_1_rdata rdata Input 16
add_interface_port rw_post_scaler_phase_buf_1 phase_out_buf_1_wraddr wraddr Output 12
add_interface_port rw_post_scaler_phase_buf_1 phase_out_buf_1_wrdata wrdata Output 16
add_interface_port rw_post_scaler_phase_buf_1 phase_out_buf_1_wren wren Output 1


# 
# connection point rw_post_scaler_mag_buf_1
# 
add_interface rw_post_scaler_mag_buf_1 conduit end
set_interface_property rw_post_scaler_mag_buf_1 associatedClock ""
set_interface_property rw_post_scaler_mag_buf_1 associatedReset ""
set_interface_property rw_post_scaler_mag_buf_1 ENABLED true
set_interface_property rw_post_scaler_mag_buf_1 EXPORT_OF ""
set_interface_property rw_post_scaler_mag_buf_1 PORT_NAME_MAP ""
set_interface_property rw_post_scaler_mag_buf_1 CMSIS_SVD_VARIABLES ""
set_interface_property rw_post_scaler_mag_buf_1 SVD_ADDRESS_GROUP ""

add_interface_port rw_post_scaler_mag_buf_1 mag_out_buf_1_raddr raddr Output 12
add_interface_port rw_post_scaler_mag_buf_1 mag_out_buf_1_rdata rdata Input 16
add_interface_port rw_post_scaler_mag_buf_1 mag_out_buf_1_wraddr wraddr Output 12
add_interface_port rw_post_scaler_mag_buf_1 mag_out_buf_1_wrdata wrdata Output 16
add_interface_port rw_post_scaler_mag_buf_1 mag_out_buf_1_wren wren Output 1


# 
# connection point rw_post_scaler_mag_buf_0
# 
add_interface rw_post_scaler_mag_buf_0 conduit end
set_interface_property rw_post_scaler_mag_buf_0 associatedClock ""
set_interface_property rw_post_scaler_mag_buf_0 associatedReset ""
set_interface_property rw_post_scaler_mag_buf_0 ENABLED true
set_interface_property rw_post_scaler_mag_buf_0 EXPORT_OF ""
set_interface_property rw_post_scaler_mag_buf_0 PORT_NAME_MAP ""
set_interface_property rw_post_scaler_mag_buf_0 CMSIS_SVD_VARIABLES ""
set_interface_property rw_post_scaler_mag_buf_0 SVD_ADDRESS_GROUP ""

add_interface_port rw_post_scaler_mag_buf_0 mag_out_buf_0_raddr raddr Output 12
add_interface_port rw_post_scaler_mag_buf_0 mag_out_buf_0_rdata rdata Input 16
add_interface_port rw_post_scaler_mag_buf_0 mag_out_buf_0_wraddr wraddr Output 12
add_interface_port rw_post_scaler_mag_buf_0 mag_out_buf_0_wrdata wrdata Output 16
add_interface_port rw_post_scaler_mag_buf_0 mag_out_buf_0_wren wren Output 1


# 
# connection point rw_synth_devs_buf
# 
add_interface rw_synth_devs_buf conduit end
set_interface_property rw_synth_devs_buf associatedClock ""
set_interface_property rw_synth_devs_buf associatedReset ""
set_interface_property rw_synth_devs_buf ENABLED true
set_interface_property rw_synth_devs_buf EXPORT_OF ""
set_interface_property rw_synth_devs_buf PORT_NAME_MAP ""
set_interface_property rw_synth_devs_buf CMSIS_SVD_VARIABLES ""
set_interface_property rw_synth_devs_buf SVD_ADDRESS_GROUP ""

add_interface_port rw_synth_devs_buf synth_devs_raddr raddr Output 12
add_interface_port rw_synth_devs_buf synth_devs_rdata rdata Input 16
add_interface_port rw_synth_devs_buf synth_devs_wraddr wraddr Output 12
add_interface_port rw_synth_devs_buf synth_devs_wrdata wrdata Output 16
add_interface_port rw_synth_devs_buf synth_devs_wren wren Output 1


# 
# connection point rw_synth_mags_buf
# 
add_interface rw_synth_mags_buf conduit end
set_interface_property rw_synth_mags_buf associatedClock ""
set_interface_property rw_synth_mags_buf associatedReset ""
set_interface_property rw_synth_mags_buf ENABLED true
set_interface_property rw_synth_mags_buf EXPORT_OF ""
set_interface_property rw_synth_mags_buf PORT_NAME_MAP ""
set_interface_property rw_synth_mags_buf CMSIS_SVD_VARIABLES ""
set_interface_property rw_synth_mags_buf SVD_ADDRESS_GROUP ""

add_interface_port rw_synth_mags_buf synth_mags_raddr raddr Output 12
add_interface_port rw_synth_mags_buf synth_mags_rdata rdata Input 16
add_interface_port rw_synth_mags_buf synth_mags_wraddr wraddr Output 12
add_interface_port rw_synth_mags_buf synth_mags_wrdata wrdata Output 16
add_interface_port rw_synth_mags_buf synth_mags_wren writeresponsevalid_n Output 1


# 
# connection point to_polar_to_cart
# 
add_interface to_polar_to_cart conduit end
set_interface_property to_polar_to_cart associatedClock ""
set_interface_property to_polar_to_cart associatedReset ""
set_interface_property to_polar_to_cart ENABLED true
set_interface_property to_polar_to_cart EXPORT_OF ""
set_interface_property to_polar_to_cart PORT_NAME_MAP ""
set_interface_property to_polar_to_cart CMSIS_SVD_VARIABLES ""
set_interface_property to_polar_to_cart SVD_ADDRESS_GROUP ""

add_interface_port to_polar_to_cart cur_buf data Output 1
add_interface_port to_polar_to_cart go_out go Output 1


# 
# connection point from_software_interface
# 
add_interface from_software_interface conduit end
set_interface_property from_software_interface associatedClock ""
set_interface_property from_software_interface associatedReset ""
set_interface_property from_software_interface ENABLED true
set_interface_property from_software_interface EXPORT_OF ""
set_interface_property from_software_interface PORT_NAME_MAP ""
set_interface_property from_software_interface CMSIS_SVD_VARIABLES ""
set_interface_property from_software_interface SVD_ADDRESS_GROUP ""

add_interface_port from_software_interface scale_amt data Input 8

