# TCL File Generated by Component Editor 21.1
# Sun May 12 05:33:59 EDT 2024
# DO NOT MODIFY


# 
# stitcher "Stitcher" v1.0
#  2024.05.12.05:33:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module stitcher
# 
set_module_property DESCRIPTION ""
set_module_property NAME stitcher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Stitcher
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stitcher
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stitcher.sv SYSTEM_VERILOG PATH components/stitcher/stitcher.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point from_iffter
# 
add_interface from_iffter conduit end
set_interface_property from_iffter associatedClock ""
set_interface_property from_iffter associatedReset ""
set_interface_property from_iffter ENABLED true
set_interface_property from_iffter EXPORT_OF ""
set_interface_property from_iffter PORT_NAME_MAP ""
set_interface_property from_iffter CMSIS_SVD_VARIABLES ""
set_interface_property from_iffter SVD_ADDRESS_GROUP ""

add_interface_port from_iffter go_in go Input 1


# 
# connection point read_rom
# 
add_interface read_rom conduit end
set_interface_property read_rom associatedClock ""
set_interface_property read_rom associatedReset ""
set_interface_property read_rom ENABLED true
set_interface_property read_rom EXPORT_OF ""
set_interface_property read_rom PORT_NAME_MAP ""
set_interface_property read_rom CMSIS_SVD_VARIABLES ""
set_interface_property read_rom SVD_ADDRESS_GROUP ""

add_interface_port read_rom hann_rom_addr addr Output 12
add_interface_port read_rom hann_rom_data data Input 16


# 
# connection point read_data
# 
add_interface read_data conduit end
set_interface_property read_data associatedClock ""
set_interface_property read_data associatedReset ""
set_interface_property read_data ENABLED true
set_interface_property read_data EXPORT_OF ""
set_interface_property read_data PORT_NAME_MAP ""
set_interface_property read_data CMSIS_SVD_VARIABLES ""
set_interface_property read_data SVD_ADDRESS_GROUP ""

add_interface_port read_data in_buf_addr addr Output 12
add_interface_port read_data in_buf_data data Input 16


# 
# connection point write_out
# 
add_interface write_out conduit end
set_interface_property write_out associatedClock ""
set_interface_property write_out associatedReset ""
set_interface_property write_out ENABLED true
set_interface_property write_out EXPORT_OF ""
set_interface_property write_out PORT_NAME_MAP ""
set_interface_property write_out CMSIS_SVD_VARIABLES ""
set_interface_property write_out SVD_ADDRESS_GROUP ""

add_interface_port write_out out_buf_addr addr Output 12
add_interface_port write_out out_buf_data data Output 16
add_interface_port write_out out_buf_wren wren Output 1


# 
# connection point to_emitter
# 
add_interface to_emitter conduit end
set_interface_property to_emitter associatedClock ""
set_interface_property to_emitter associatedReset ""
set_interface_property to_emitter ENABLED true
set_interface_property to_emitter EXPORT_OF ""
set_interface_property to_emitter PORT_NAME_MAP ""
set_interface_property to_emitter CMSIS_SVD_VARIABLES ""
set_interface_property to_emitter SVD_ADDRESS_GROUP ""

add_interface_port to_emitter window_start data Output 2
add_interface_port to_emitter go_out go Output 1

