# TCL File Generated by Component Editor 21.1
# Sun May 12 04:04:56 EDT 2024
# DO NOT MODIFY


# 
# synth_buf "Synth Buf" v1.0
#  2024.05.12.04:04:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module synth_buf
# 
set_module_property DESCRIPTION ""
set_module_property NAME synth_buf
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Synth Buf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL synth_buf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file synth_buf.v VERILOG PATH components/memblocks/synth_buf/synth_buf.v TOP_LEVEL_FILE
add_fileset_file synth_buf_bb.v VERILOG PATH components/memblocks/synth_buf/synth_buf_bb.v
add_fileset_file synth_buf_inst.v VERILOG PATH components/memblocks/synth_buf/synth_buf_inst.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clock clk Input 1


# 
# connection point to_scaler
# 
add_interface to_scaler conduit end
set_interface_property to_scaler associatedClock ""
set_interface_property to_scaler associatedReset ""
set_interface_property to_scaler ENABLED true
set_interface_property to_scaler EXPORT_OF ""
set_interface_property to_scaler PORT_NAME_MAP ""
set_interface_property to_scaler CMSIS_SVD_VARIABLES ""
set_interface_property to_scaler SVD_ADDRESS_GROUP ""

add_interface_port to_scaler address raddr Input 12
add_interface_port to_scaler data wrdata Input 16
add_interface_port to_scaler wren wren Input 1
add_interface_port to_scaler q rdata Output 16
add_interface_port to_scaler manual_address wraddr Input 12

